version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <MYSQL_PASSWORD>   # replace this
      MYSQL_DATABASE: <MYSQL_DATABASE_NAME> # replace this
      MYSQL_PASSWORD: <MYSQL_PASSWORD>    # replace this
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - main
  
  redis_host:
    image: redis:latest
    restart: always
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - main

  flask_app:
    build: ./backend
    expose:
      - 5000
    links:
      - mysql:mysql
      - redis_host:redis_host
    depends_on:
      - mysql
      - redis_host
    environment:
      SECRET_KEY: <SECRET_KEY>  # replace this
      MYSQL_HOST: mysql    # Use the service name as the host
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: <MYSQL_PASSWORD>  # replace this
      MYSQL_ADMIN_ACCOUNT: adminAccount
      MYSQL_ADMIN_PASSWORD: <ADMIN_ACCOUNT_PASSWORD>   # replace this and admin account password in init script
      MYSQL_STAFF_ACCOUNT: staffAccount
      MYSQL_STAFF_PASSWORD: <STAFF_ACCOUNT_PASSWORD>   # replace this and staff account password in init script
      MYSQL_REGISTERED_USER_ACCOUNT: registeredUserAccount
      MYSQL_REGISTERED_USER_PASSWORD: <REGISTERED_USER_ACCOUNT_PASSWORD>   # replace this and registered user account password in init script
      MYSQL_GUEST_USER_ACCOUNT: guestAccount
      MYSQL_GUEST_USER_PASSWORD: <GUEST_ACCOUNT_PASSWORD>  # replace this and guest user account password in init script
      MYSQL_DB: <MYSQL_DATABASE_NAME>  # replace this
      REDIS_HOST: redis_host   # Use the service name as the host
      REDIS_PORT: 6379
      INIT_ENABLED: 1
    networks:
      - main

  react_app:
    build: ./frontend
    expose:
      - 3000
    depends_on:
      - flask_app
    environment:
      REACT_APP_BACKEND_API_URL: http://localhost/api  # Communication will be done not within container network but through host network. So use localhost instead of service name.
    networks:
      - main

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    links:
      - flask_app:flask_app
      - react_app:react_app
    depends_on:
      - flask_app
      - react_app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
